insert into car (make, model, year_of_release) values ('Honda', 'Odyssey', 2007);
insert into car (make, model, year_of_release) values ('Ford', 'Ranger', 1994);
insert into car (make, model, year_of_release) values ('Suzuki', 'XL7', 2006);
insert into car (make, model, year_of_release) values ('Nissan', 'Frontier', 1999);
insert into car (make, model, year_of_release) values ('Volkswagen', 'Golf', 1988);
insert into car (make, model, year_of_release) values ('Lincoln', 'MKT', 2011);
insert into car (make, model, year_of_release) values ('Dodge', 'Intrepid', 2001);
insert into car (make, model, year_of_release) values ('Suzuki', 'SJ', 1987);
insert into car (make, model, year_of_release) values ('Rolls-Royce', 'Ghost', 2012);
insert into car (make, model, year_of_release) values ('Mazda', '929', 1995);
insert into car (make, model, year_of_release) values ('Audi', 'A5', 2011);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Cobalt SS', 2008);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Suburban 2500', 2012);
insert into car (make, model, year_of_release) values ('Audi', 'TT', 2005);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', 'SL-Class', 2012);
insert into car (make, model, year_of_release) values ('Lexus', 'LS Hybrid', 2011);
insert into car (make, model, year_of_release) values ('Cadillac', 'STS', 2005);
insert into car (make, model, year_of_release) values ('Audi', 'A6', 2003);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Blazer', 1993);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', 'C-Class', 2009);
insert into car (make, model, year_of_release) values ('Audi', 'S6', 2009);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', 'G-Class', 2012);
insert into car (make, model, year_of_release) values ('Audi', '4000CS Quattro', 1987);
insert into car (make, model, year_of_release) values ('Ford', 'Focus', 2010);
insert into car (make, model, year_of_release) values ('Ferrari', '612 Scaglietti', 2008);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Tahoe', 1996);
insert into car (make, model, year_of_release) values ('GMC', 'Yukon', 2004);
insert into car (make, model, year_of_release) values ('Maybach', '57', 2008);
insert into car (make, model, year_of_release) values ('Land Rover', 'Discovery', 2004);
insert into car (make, model, year_of_release) values ('Ford', 'Expedition EL', 2009);
insert into car (make, model, year_of_release) values ('Bentley', 'Continental', 2009);
insert into car (make, model, year_of_release) values ('Ford', 'F-Series', 2011);
insert into car (make, model, year_of_release) values ('GMC', 'Yukon XL 1500', 2006);
insert into car (make, model, year_of_release) values ('Ford', 'F250', 2000);
insert into car (make, model, year_of_release) values ('Kia', 'Sedona', 2006);
insert into car (make, model, year_of_release) values ('GMC', 'Envoy', 2004);
insert into car (make, model, year_of_release) values ('Volvo', 'C70', 2011);
insert into car (make, model, year_of_release) values ('Pontiac', 'Firebird', 1991);
insert into car (make, model, year_of_release) values ('Cadillac', 'Eldorado', 1999);
insert into car (make, model, year_of_release) values ('Jaguar', 'XJ Series', 1994);
insert into car (make, model, year_of_release) values ('Saab', '9-5', 2003);
insert into car (make, model, year_of_release) values ('Hyundai', 'Elantra', 2007);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Tahoe', 2013);
insert into car (make, model, year_of_release) values ('Scion', 'tC', 2011);
insert into car (make, model, year_of_release) values ('Aston Martin', 'DB9', 2009);
insert into car (make, model, year_of_release) values ('Suzuki', 'Forenza', 2006);
insert into car (make, model, year_of_release) values ('Volvo', 'V40', 2000);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Suburban 2500', 1992);
insert into car (make, model, year_of_release) values ('Toyota', 'Tundra', 2007);
insert into car (make, model, year_of_release) values ('Cadillac', 'Escalade EXT', 2006);
insert into car (make, model, year_of_release) values ('Lexus', 'ES', 1991);
insert into car (make, model, year_of_release) values ('Subaru', 'Baja', 2004);
insert into car (make, model, year_of_release) values ('GMC', 'Envoy', 2009);
insert into car (make, model, year_of_release) values ('Jaguar', 'XK', 2009);
insert into car (make, model, year_of_release) values ('Toyota', '4Runner', 2002);
insert into car (make, model, year_of_release) values ('GMC', 'Envoy', 2005);
insert into car (make, model, year_of_release) values ('Cadillac', 'DeVille', 1999);
insert into car (make, model, year_of_release) values ('Lexus', 'LS', 2001);
insert into car (make, model, year_of_release) values ('Subaru', 'Forester', 2000);
insert into car (make, model, year_of_release) values ('Suzuki', 'Daewoo Magnus', 2005);
insert into car (make, model, year_of_release) values ('Ford', 'E150', 2004);
insert into car (make, model, year_of_release) values ('Scion', 'xD', 2008);
insert into car (make, model, year_of_release) values ('Plymouth', 'Laser', 1990);
insert into car (make, model, year_of_release) values ('Mercury', 'Capri', 1992);
insert into car (make, model, year_of_release) values ('BMW', 'Alpina B7', 2008);
insert into car (make, model, year_of_release) values ('Nissan', 'Maxima', 1998);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Corsica', 1994);
insert into car (make, model, year_of_release) values ('Spyker', 'C8 Laviolette', 2004);
insert into car (make, model, year_of_release) values ('Suzuki', 'Aerio', 2007);
insert into car (make, model, year_of_release) values ('Pontiac', 'Bonneville', 1994);
insert into car (make, model, year_of_release) values ('Porsche', 'Cayenne', 2008);
insert into car (make, model, year_of_release) values ('Cadillac', 'STS', 2010);
insert into car (make, model, year_of_release) values ('Lotus', 'Exige', 2007);
insert into car (make, model, year_of_release) values ('Buick', 'Park Avenue', 1991);
insert into car (make, model, year_of_release) values ('Ford', 'Escort', 2002);
insert into car (make, model, year_of_release) values ('Jeep', 'Commander', 2008);
insert into car (make, model, year_of_release) values ('Subaru', 'B9 Tribeca', 2006);
insert into car (make, model, year_of_release) values ('Chrysler', 'Sebring', 1999);
insert into car (make, model, year_of_release) values ('Volkswagen', 'GTI', 2007);
insert into car (make, model, year_of_release) values ('Subaru', 'XT', 1990);
insert into car (make, model, year_of_release) values ('Mercury', 'Tracer', 1991);
insert into car (make, model, year_of_release) values ('Subaru', 'Forester', 1998);
insert into car (make, model, year_of_release) values ('GMC', 'Envoy', 2002);
insert into car (make, model, year_of_release) values ('Pontiac', 'LeMans', 1991);
insert into car (make, model, year_of_release) values ('Holden', 'VS Commodore', 1997);
insert into car (make, model, year_of_release) values ('Ford', 'Escort', 1992);
insert into car (make, model, year_of_release) values ('Buick', 'LeSabre', 1985);
insert into car (make, model, year_of_release) values ('GMC', 'Safari', 2000);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', '300SL', 1992);
insert into car (make, model, year_of_release) values ('Saab', '9-5', 1999);
insert into car (make, model, year_of_release) values ('Buick', 'Skylark', 1992);
insert into car (make, model, year_of_release) values ('MINI', 'Clubman', 2010);
insert into car (make, model, year_of_release) values ('Jeep', 'Commander', 2007);
insert into car (make, model, year_of_release) values ('Toyota', 'Sequoia', 2010);
insert into car (make, model, year_of_release) values ('Volkswagen', 'Fox', 1993);
insert into car (make, model, year_of_release) values ('Subaru', 'Alcyone SVX', 1994);
insert into car (make, model, year_of_release) values ('Buick', 'LaCrosse', 2009);
insert into car (make, model, year_of_release) values ('Plymouth', 'Voyager', 1997);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Cobalt', 2007);
insert into car (make, model, year_of_release) values ('Pontiac', 'Sunfire', 1998);
insert into car (make, model, year_of_release) values ('Mazda', 'Mazda5', 2009);
insert into car (make, model, year_of_release) values ('Ford', 'Club Wagon', 1995);
insert into car (make, model, year_of_release) values ('Cadillac', 'Allante', 1992);
insert into car (make, model, year_of_release) values ('Volkswagen', 'Type 2', 1987);
insert into car (make, model, year_of_release) values ('Dodge', 'Ram 2500', 2001);
insert into car (make, model, year_of_release) values ('Dodge', 'Charger', 1968);
insert into car (make, model, year_of_release) values ('BMW', 'Z4', 2003);
insert into car (make, model, year_of_release) values ('Volkswagen', 'Golf', 1998);
insert into car (make, model, year_of_release) values ('GMC', 'Savana 3500', 2012);
insert into car (make, model, year_of_release) values ('Porsche', '911', 1999);
insert into car (make, model, year_of_release) values ('Plymouth', 'Neon', 1996);
insert into car (make, model, year_of_release) values ('Porsche', '968', 1994);
insert into car (make, model, year_of_release) values ('Buick', 'LeSabre', 1995);
insert into car (make, model, year_of_release) values ('Ford', 'Expedition', 2008);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', 'W201', 1985);
insert into car (make, model, year_of_release) values ('Foose', 'Hemisfear', 2007);
insert into car (make, model, year_of_release) values ('Pontiac', 'Torrent', 2007);
insert into car (make, model, year_of_release) values ('Audi', 'RS4', 2008);
insert into car (make, model, year_of_release) values ('BMW', '330', 2006);
insert into car (make, model, year_of_release) values ('Kia', 'Spectra', 2005);
insert into car (make, model, year_of_release) values ('GMC', 'Sonoma Club Coupe', 1996);
insert into car (make, model, year_of_release) values ('Holden', 'VS Commodore', 1995);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Silverado 3500', 2012);
insert into car (make, model, year_of_release) values ('Volvo', 'S60', 2001);
insert into car (make, model, year_of_release) values ('Toyota', 'Celica', 2005);
insert into car (make, model, year_of_release) values ('Audi', 'S5', 2011);
insert into car (make, model, year_of_release) values ('Chevrolet', 'S10', 1992);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Suburban 1500', 2003);
insert into car (make, model, year_of_release) values ('Volkswagen', 'Corrado', 1991);
insert into car (make, model, year_of_release) values ('Ford', 'Explorer', 2012);
insert into car (make, model, year_of_release) values ('Volkswagen', 'Golf', 1986);
insert into car (make, model, year_of_release) values ('Lincoln', 'Continental', 1995);
insert into car (make, model, year_of_release) values ('Ford', 'Crown Victoria', 2007);
insert into car (make, model, year_of_release) values ('Toyota', 'Celica', 2005);
insert into car (make, model, year_of_release) values ('GMC', '3500', 1995);
insert into car (make, model, year_of_release) values ('Lamborghini', 'Diablo', 1996);
insert into car (make, model, year_of_release) values ('BMW', '645', 2005);
insert into car (make, model, year_of_release) values ('Nissan', 'Altima', 2001);
insert into car (make, model, year_of_release) values ('Buick', 'Park Avenue', 2005);
insert into car (make, model, year_of_release) values ('Volvo', '940', 1992);
insert into car (make, model, year_of_release) values ('Jaguar', 'XJ Series', 1996);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Avalanche', 2011);
insert into car (make, model, year_of_release) values ('Volvo', '850', 1997);
insert into car (make, model, year_of_release) values ('Honda', 'Odyssey', 2006);
insert into car (make, model, year_of_release) values ('Volkswagen', 'Passat', 2006);
insert into car (make, model, year_of_release) values ('Mazda', 'B-Series', 2005);
insert into car (make, model, year_of_release) values ('Ford', 'F450', 2008);
insert into car (make, model, year_of_release) values ('Nissan', 'Quest', 1996);
insert into car (make, model, year_of_release) values ('GMC', 'Envoy', 2002);
insert into car (make, model, year_of_release) values ('BMW', '525', 2001);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'Pajero', 2004);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', '600SEC', 1993);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', 'SLK-Class', 2004);
insert into car (make, model, year_of_release) values ('Subaru', 'Legacy', 2006);
insert into car (make, model, year_of_release) values ('Pontiac', 'Montana', 2005);
insert into car (make, model, year_of_release) values ('Volvo', 'XC90', 2010);
insert into car (make, model, year_of_release) values ('Ford', 'Fusion', 2011);
insert into car (make, model, year_of_release) values ('Mazda', 'B-Series', 2003);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Corvette', 1972);
insert into car (make, model, year_of_release) values ('Subaru', 'Legacy', 1994);
insert into car (make, model, year_of_release) values ('Audi', 'S5', 2011);
insert into car (make, model, year_of_release) values ('Lincoln', 'MKX', 2008);
insert into car (make, model, year_of_release) values ('Volvo', 'S80', 2008);
insert into car (make, model, year_of_release) values ('Subaru', 'Impreza', 1995);
insert into car (make, model, year_of_release) values ('Nissan', 'Pathfinder', 2010);
insert into car (make, model, year_of_release) values ('Lamborghini', 'Diablo', 1990);
insert into car (make, model, year_of_release) values ('Dodge', 'Caravan', 2004);
insert into car (make, model, year_of_release) values ('Subaru', 'XT', 1987);
insert into car (make, model, year_of_release) values ('Porsche', '911', 2002);
insert into car (make, model, year_of_release) values ('Isuzu', 'i-Series', 2008);
insert into car (make, model, year_of_release) values ('Toyota', 'MR2', 1992);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Silverado 3500', 2005);
insert into car (make, model, year_of_release) values ('Lexus', 'LS', 1996);
insert into car (make, model, year_of_release) values ('Pontiac', 'Firefly', 1995);
insert into car (make, model, year_of_release) values ('MINI', 'Cooper', 2008);
insert into car (make, model, year_of_release) values ('Buick', 'Roadmaster', 1995);
insert into car (make, model, year_of_release) values ('Land Rover', 'Freelander', 2003);
insert into car (make, model, year_of_release) values ('Dodge', 'Ram 2500 Club', 1995);
insert into car (make, model, year_of_release) values ('Nissan', '240SX', 1997);
insert into car (make, model, year_of_release) values ('Audi', 'S4', 2006);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Avalanche 1500', 2003);
insert into car (make, model, year_of_release) values ('Porsche', '911', 2000);
insert into car (make, model, year_of_release) values ('Pontiac', '6000', 1984);
insert into car (make, model, year_of_release) values ('Bentley', 'Arnage', 2006);
insert into car (make, model, year_of_release) values ('Dodge', 'Intrepid', 2004);
insert into car (make, model, year_of_release) values ('Plymouth', 'Laser', 1991);
insert into car (make, model, year_of_release) values ('Volkswagen', 'Eurovan', 1993);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'Pajero', 1997);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Express 2500', 1997);
insert into car (make, model, year_of_release) values ('Chrysler', 'Sebring', 2010);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', 'W201', 1984);
insert into car (make, model, year_of_release) values ('Plymouth', 'Voyager', 2000);
insert into car (make, model, year_of_release) values ('Suzuki', 'Grand Vitara', 2002);
insert into car (make, model, year_of_release) values ('Chevrolet', 'G-Series 3500', 1997);
insert into car (make, model, year_of_release) values ('Dodge', 'Charger', 2006);
insert into car (make, model, year_of_release) values ('Ford', 'LTD Crown Victoria', 1988);
insert into car (make, model, year_of_release) values ('Ford', 'Taurus', 2012);
insert into car (make, model, year_of_release) values ('Dodge', 'Ram 1500', 1995);
insert into car (make, model, year_of_release) values ('Buick', 'Skylark', 1993);
insert into car (make, model, year_of_release) values ('Cadillac', 'CTS-V', 2010);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'Eclipse', 2004);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', 'SLK-Class', 2006);
insert into car (make, model, year_of_release) values ('Chevrolet', 'HHR', 2010);
insert into car (make, model, year_of_release) values ('Ford', 'F250', 2000);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'Montero Sport', 1999);
insert into car (make, model, year_of_release) values ('Ford', 'Thunderbird', 1995);
insert into car (make, model, year_of_release) values ('Cadillac', 'Catera', 1998);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Cruze', 2013);
insert into car (make, model, year_of_release) values ('Oldsmobile', 'Bravada', 2004);
insert into car (make, model, year_of_release) values ('Ford', 'Taurus', 1995);
insert into car (make, model, year_of_release) values ('Volkswagen', 'GTI', 1990);
insert into car (make, model, year_of_release) values ('Mercury', 'Mountaineer', 2007);
insert into car (make, model, year_of_release) values ('BMW', '745', 2005);
insert into car (make, model, year_of_release) values ('Honda', 'CR-V', 2006);
insert into car (make, model, year_of_release) values ('Suzuki', 'Equator', 2009);
insert into car (make, model, year_of_release) values ('Mazda', 'MX-3', 1994);
insert into car (make, model, year_of_release) values ('Hummer', 'H2', 2009);
insert into car (make, model, year_of_release) values ('Plymouth', 'Sundance', 1992);
insert into car (make, model, year_of_release) values ('Pontiac', 'G8', 2009);
insert into car (make, model, year_of_release) values ('BMW', '7 Series', 1996);
insert into car (make, model, year_of_release) values ('Toyota', 'Tundra', 2001);
insert into car (make, model, year_of_release) values ('Cadillac', 'XLR-V', 2006);
insert into car (make, model, year_of_release) values ('Buick', 'Roadmaster', 1994);
insert into car (make, model, year_of_release) values ('Buick', 'LeSabre', 2001);
insert into car (make, model, year_of_release) values ('Buick', 'Lucerne', 2011);
insert into car (make, model, year_of_release) values ('Jensen', 'Interceptor', 1966);
insert into car (make, model, year_of_release) values ('Lotus', 'Evora', 2012);
insert into car (make, model, year_of_release) values ('Pontiac', 'Grand Am', 2000);
insert into car (make, model, year_of_release) values ('GMC', 'Savana 3500', 2003);
insert into car (make, model, year_of_release) values ('Volvo', '960', 1994);
insert into car (make, model, year_of_release) values ('Suzuki', 'Forenza', 2006);
insert into car (make, model, year_of_release) values ('Isuzu', 'Rodeo Sport', 2003);
insert into car (make, model, year_of_release) values ('Land Rover', 'Freelander', 2002);
insert into car (make, model, year_of_release) values ('Dodge', 'Ram', 2011);
insert into car (make, model, year_of_release) values ('Ford', 'Taurus', 1991);
insert into car (make, model, year_of_release) values ('Nissan', 'Xterra', 2011);
insert into car (make, model, year_of_release) values ('Suzuki', 'Sidekick', 1994);
insert into car (make, model, year_of_release) values ('Jaguar', 'XK Series', 2005);
insert into car (make, model, year_of_release) values ('Ford', 'Expedition EL', 2012);
insert into car (make, model, year_of_release) values ('Suzuki', 'Swift', 2006);
insert into car (make, model, year_of_release) values ('Ford', 'F250', 2009);
insert into car (make, model, year_of_release) values ('Porsche', 'Cayenne', 2010);
insert into car (make, model, year_of_release) values ('Audi', 'A6', 2008);
insert into car (make, model, year_of_release) values ('Pontiac', 'G6', 2009);
insert into car (make, model, year_of_release) values ('Oldsmobile', 'Alero', 1999);
insert into car (make, model, year_of_release) values ('Nissan', '200SX', 1995);
insert into car (make, model, year_of_release) values ('Audi', '90', 1988);
insert into car (make, model, year_of_release) values ('Mercury', 'Villager', 1999);
insert into car (make, model, year_of_release) values ('Lamborghini', 'Diablo', 1990);
insert into car (make, model, year_of_release) values ('Toyota', 'MR2', 2005);
insert into car (make, model, year_of_release) values ('Jeep', 'Wrangler', 2009);
insert into car (make, model, year_of_release) values ('Acura', 'Integra', 1993);
insert into car (make, model, year_of_release) values ('MINI', 'Clubman', 2009);
insert into car (make, model, year_of_release) values ('Jaguar', 'XK Series', 2001);
insert into car (make, model, year_of_release) values ('Audi', 'S8', 2009);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Monte Carlo', 1998);
insert into car (make, model, year_of_release) values ('Acura', 'RL', 2008);
insert into car (make, model, year_of_release) values ('Infiniti', 'G37', 2010);
insert into car (make, model, year_of_release) values ('Plymouth', 'Acclaim', 1994);
insert into car (make, model, year_of_release) values ('Mazda', 'MX-5', 1994);
insert into car (make, model, year_of_release) values ('Lotus', 'Elan', 1991);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Beretta', 1994);
insert into car (make, model, year_of_release) values ('Jaguar', 'S-Type', 2003);
insert into car (make, model, year_of_release) values ('Land Rover', 'Range Rover', 2002);
insert into car (make, model, year_of_release) values ('Aston Martin', 'DB9', 2008);
insert into car (make, model, year_of_release) values ('Suzuki', 'Samurai', 1994);
insert into car (make, model, year_of_release) values ('Volkswagen', 'Golf', 1986);
insert into car (make, model, year_of_release) values ('Ford', 'E150', 2004);
insert into car (make, model, year_of_release) values ('Pontiac', 'Montana', 2004);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Silverado 2500', 2007);
insert into car (make, model, year_of_release) values ('Dodge', 'Grand Caravan', 1994);
insert into car (make, model, year_of_release) values ('Ford', 'Ranger', 1991);
insert into car (make, model, year_of_release) values ('Dodge', 'Caravan', 2004);
insert into car (make, model, year_of_release) values ('Mazda', 'MPV', 1990);
insert into car (make, model, year_of_release) values ('Mazda', 'RX-8', 2006);
insert into car (make, model, year_of_release) values ('Land Rover', 'Discovery Series II', 2002);
insert into car (make, model, year_of_release) values ('Pontiac', 'Firebird Trans Am', 1986);
insert into car (make, model, year_of_release) values ('Mercury', 'Tracer', 1993);
insert into car (make, model, year_of_release) values ('Cadillac', 'Seville', 1996);
insert into car (make, model, year_of_release) values ('Plymouth', 'Grand Voyager', 1994);
insert into car (make, model, year_of_release) values ('Subaru', 'Legacy', 1998);
insert into car (make, model, year_of_release) values ('BMW', '3 Series', 2012);
insert into car (make, model, year_of_release) values ('Dodge', 'Ram 3500 Club', 1997);
insert into car (make, model, year_of_release) values ('Plymouth', 'Grand Voyager', 1995);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', 'S-Class', 2002);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', 'C-Class', 1994);
insert into car (make, model, year_of_release) values ('Lotus', 'Esprit', 1985);
insert into car (make, model, year_of_release) values ('GMC', 'Savana', 2011);
insert into car (make, model, year_of_release) values ('Hyundai', 'Genesis', 2011);
insert into car (make, model, year_of_release) values ('Nissan', '350Z', 2007);
insert into car (make, model, year_of_release) values ('Dodge', 'Stealth', 1993);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Bel Air', 1967);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', '300E', 1993);
insert into car (make, model, year_of_release) values ('Dodge', 'Ram 1500 Club', 1995);
insert into car (make, model, year_of_release) values ('Oldsmobile', 'Regency', 1998);
insert into car (make, model, year_of_release) values ('Bentley', 'Continental GTC', 2009);
insert into car (make, model, year_of_release) values ('MINI', 'Cooper', 2004);
insert into car (make, model, year_of_release) values ('Dodge', 'Nitro', 2010);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', 'SLK-Class', 2006);
insert into car (make, model, year_of_release) values ('Hummer', 'H1', 2001);
insert into car (make, model, year_of_release) values ('Volvo', 'S40', 2009);
insert into car (make, model, year_of_release) values ('Honda', 'Civic', 2003);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'Chariot', 1996);
insert into car (make, model, year_of_release) values ('Ford', 'Focus', 2007);
insert into car (make, model, year_of_release) values ('Cadillac', 'DeVille', 1996);
insert into car (make, model, year_of_release) values ('Dodge', 'Stealth', 1994);
insert into car (make, model, year_of_release) values ('Maserati', 'Quattroporte', 2011);
insert into car (make, model, year_of_release) values ('Ford', 'Ranger', 2006);
insert into car (make, model, year_of_release) values ('Ford', 'Thunderbird', 1985);
insert into car (make, model, year_of_release) values ('GMC', '1500 Club Coupe', 1999);
insert into car (make, model, year_of_release) values ('Mazda', 'CX-9', 2007);
insert into car (make, model, year_of_release) values ('Mercury', 'Grand Marquis', 1987);
insert into car (make, model, year_of_release) values ('Oldsmobile', 'Silhouette', 2002);
insert into car (make, model, year_of_release) values ('Volvo', 'XC90', 2003);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Tahoe', 2009);
insert into car (make, model, year_of_release) values ('Cadillac', 'DeVille', 2001);
insert into car (make, model, year_of_release) values ('Dodge', 'Intrepid', 1996);
insert into car (make, model, year_of_release) values ('Ford', 'Econoline E250', 1994);
insert into car (make, model, year_of_release) values ('Buick', 'Terraza', 2005);
insert into car (make, model, year_of_release) values ('GMC', 'Yukon', 2009);
insert into car (make, model, year_of_release) values ('Kia', 'Spectra', 2006);
insert into car (make, model, year_of_release) values ('Buick', 'Reatta', 1989);
insert into car (make, model, year_of_release) values ('Toyota', 'Yaris', 2009);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', 'SLK-Class', 1999);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Corvette', 1964);
insert into car (make, model, year_of_release) values ('Kia', 'Sportage', 1996);
insert into car (make, model, year_of_release) values ('Land Rover', 'LR3', 2008);
insert into car (make, model, year_of_release) values ('Pontiac', 'Montana', 2002);
insert into car (make, model, year_of_release) values ('Honda', 'del Sol', 1993);
insert into car (make, model, year_of_release) values ('Audi', 'Quattro', 1985);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Monte Carlo', 1997);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', 'M-Class', 1998);
insert into car (make, model, year_of_release) values ('Ford', 'Bronco', 1987);
insert into car (make, model, year_of_release) values ('Dodge', 'Ram Van B350', 1994);
insert into car (make, model, year_of_release) values ('Pontiac', 'Grand Am', 1993);
insert into car (make, model, year_of_release) values ('Pontiac', 'Grand Am', 2001);
insert into car (make, model, year_of_release) values ('Ford', 'Transit Connect', 2012);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Corvette', 2003);
insert into car (make, model, year_of_release) values ('Ford', 'Thunderbird', 1972);
insert into car (make, model, year_of_release) values ('Dodge', 'Ram 1500', 2006);
insert into car (make, model, year_of_release) values ('Oldsmobile', 'Alero', 2003);
insert into car (make, model, year_of_release) values ('Acura', 'NSX', 2001);
insert into car (make, model, year_of_release) values ('Volkswagen', 'Eurovan', 1995);
insert into car (make, model, year_of_release) values ('Hyundai', 'Elantra', 2007);
insert into car (make, model, year_of_release) values ('Land Rover', 'Discovery', 2012);
insert into car (make, model, year_of_release) values ('Isuzu', 'i-Series', 2007);
insert into car (make, model, year_of_release) values ('Pontiac', 'Grand Prix', 1974);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Sportvan G20', 1994);
insert into car (make, model, year_of_release) values ('Volkswagen', 'Corrado', 1992);
insert into car (make, model, year_of_release) values ('Subaru', 'Forester', 2011);
insert into car (make, model, year_of_release) values ('Mercury', 'Milan', 2006);
insert into car (make, model, year_of_release) values ('Ford', 'E150', 2008);
insert into car (make, model, year_of_release) values ('Volvo', 'S80', 2008);
insert into car (make, model, year_of_release) values ('Honda', 'Ridgeline', 2009);
insert into car (make, model, year_of_release) values ('Ford', 'F250', 2010);
insert into car (make, model, year_of_release) values ('Honda', 'S2000', 2008);
insert into car (make, model, year_of_release) values ('Jaguar', 'XJ', 2006);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'Eclipse', 2009);
insert into car (make, model, year_of_release) values ('Lincoln', 'Continental Mark VII', 1986);
insert into car (make, model, year_of_release) values ('GMC', 'Yukon XL 2500', 2005);
insert into car (make, model, year_of_release) values ('Audi', '5000CS Quattro', 1986);
insert into car (make, model, year_of_release) values ('Isuzu', 'Rodeo', 2003);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Express 1500', 2010);
insert into car (make, model, year_of_release) values ('Dodge', 'Sprinter', 2006);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', 'CL-Class', 2001);
insert into car (make, model, year_of_release) values ('Hummer', 'H1', 1995);
insert into car (make, model, year_of_release) values ('Buick', 'Coachbuilder', 1993);
insert into car (make, model, year_of_release) values ('Ford', 'E250', 1984);
insert into car (make, model, year_of_release) values ('GMC', 'Vandura 3500', 1992);
insert into car (make, model, year_of_release) values ('GMC', 'Jimmy', 1996);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', 'SLK-Class', 2012);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'Montero', 2006);
insert into car (make, model, year_of_release) values ('Buick', 'LaCrosse', 2012);
insert into car (make, model, year_of_release) values ('Plymouth', 'Reliant', 1981);
insert into car (make, model, year_of_release) values ('Honda', 'Civic', 2012);
insert into car (make, model, year_of_release) values ('Lincoln', 'Town Car', 1987);
insert into car (make, model, year_of_release) values ('Ford', 'Bronco', 1984);
insert into car (make, model, year_of_release) values ('Ford', 'F-Series', 1995);
insert into car (make, model, year_of_release) values ('Buick', 'LaCrosse', 2011);
insert into car (make, model, year_of_release) values ('Dodge', 'Ram Van 1500', 2001);
insert into car (make, model, year_of_release) values ('Ford', 'Probe', 1989);
insert into car (make, model, year_of_release) values ('Toyota', 'Tacoma', 2002);
insert into car (make, model, year_of_release) values ('Hyundai', 'Genesis', 2011);
insert into car (make, model, year_of_release) values ('Buick', 'Century', 1994);
insert into car (make, model, year_of_release) values ('Nissan', 'Frontier', 2004);
insert into car (make, model, year_of_release) values ('Mercury', 'Villager', 1997);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'Mighty Max', 1995);
insert into car (make, model, year_of_release) values ('Citroën', 'CX', 1989);
insert into car (make, model, year_of_release) values ('Dodge', 'Durango', 1999);
insert into car (make, model, year_of_release) values ('Nissan', 'Versa', 2007);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Lumina', 2000);
insert into car (make, model, year_of_release) values ('Ferrari', 'F430', 2007);
insert into car (make, model, year_of_release) values ('Aston Martin', 'DB9', 2010);
insert into car (make, model, year_of_release) values ('Toyota', 'RAV4', 2006);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'Mighty Max', 1992);
insert into car (make, model, year_of_release) values ('Ford', 'Edge', 2009);
insert into car (make, model, year_of_release) values ('Oldsmobile', 'Achieva', 1994);
insert into car (make, model, year_of_release) values ('GMC', 'Sierra', 2012);
insert into car (make, model, year_of_release) values ('Toyota', 'Sienna', 2011);
insert into car (make, model, year_of_release) values ('Lincoln', 'Town Car', 1987);
insert into car (make, model, year_of_release) values ('Nissan', 'Quest', 1996);
insert into car (make, model, year_of_release) values ('BMW', 'M3', 2008);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', 'SL-Class', 2012);
insert into car (make, model, year_of_release) values ('Porsche', '928', 1993);
insert into car (make, model, year_of_release) values ('Ford', 'Ranger', 1994);
insert into car (make, model, year_of_release) values ('Ford', 'Explorer Sport Trac', 2008);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'Expo', 1993);
insert into car (make, model, year_of_release) values ('Hummer', 'H1', 1993);
insert into car (make, model, year_of_release) values ('Subaru', 'Impreza', 2011);
insert into car (make, model, year_of_release) values ('Ford', 'Freestar', 2006);
insert into car (make, model, year_of_release) values ('Mercury', 'Mariner', 2009);
insert into car (make, model, year_of_release) values ('Honda', 'S2000', 2009);
insert into car (make, model, year_of_release) values ('Volkswagen', 'Golf', 1976);
insert into car (make, model, year_of_release) values ('Chrysler', 'Town & Country', 2004);
insert into car (make, model, year_of_release) values ('Jeep', 'Grand Cherokee', 2000);
insert into car (make, model, year_of_release) values ('Ford', 'Explorer Sport', 2001);
insert into car (make, model, year_of_release) values ('Morgan', 'Aero 8', 2007);
insert into car (make, model, year_of_release) values ('Mercury', 'Topaz', 1989);
insert into car (make, model, year_of_release) values ('Lincoln', 'Mark VII', 1984);
insert into car (make, model, year_of_release) values ('Toyota', 'TundraMax', 2010);
insert into car (make, model, year_of_release) values ('Mazda', 'B-Series', 2001);
insert into car (make, model, year_of_release) values ('Acura', 'CL', 1998);
insert into car (make, model, year_of_release) values ('Aston Martin', 'DB9', 2010);
insert into car (make, model, year_of_release) values ('Nissan', 'Titan', 2008);
insert into car (make, model, year_of_release) values ('Nissan', 'Maxima', 1992);
insert into car (make, model, year_of_release) values ('Toyota', 'Paseo', 1995);
insert into car (make, model, year_of_release) values ('BMW', '3 Series', 1996);
insert into car (make, model, year_of_release) values ('Audi', 'S6', 2009);
insert into car (make, model, year_of_release) values ('Audi', 'S8', 2002);
insert into car (make, model, year_of_release) values ('Ford', 'Econoline E350', 1999);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'i-MiEV', 2012);
insert into car (make, model, year_of_release) values ('Volkswagen', 'Corrado', 1993);
insert into car (make, model, year_of_release) values ('Land Rover', 'Range Rover', 1987);
insert into car (make, model, year_of_release) values ('Volvo', 'S60', 2003);
insert into car (make, model, year_of_release) values ('Ford', 'Econoline E350', 1996);
insert into car (make, model, year_of_release) values ('Volvo', 'V50', 2010);
insert into car (make, model, year_of_release) values ('Plymouth', 'Laser', 1994);
insert into car (make, model, year_of_release) values ('Mercury', 'Mystique', 1999);
insert into car (make, model, year_of_release) values ('Volkswagen', 'Passat', 2007);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'Eclipse', 1995);
insert into car (make, model, year_of_release) values ('GMC', '1500 Club Coupe', 1994);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Impala SS', 1994);
insert into car (make, model, year_of_release) values ('GMC', 'Yukon', 2007);
insert into car (make, model, year_of_release) values ('Porsche', '944', 1985);
insert into car (make, model, year_of_release) values ('Ford', 'Escape', 2012);
insert into car (make, model, year_of_release) values ('Ford', 'E-Series', 2005);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Camaro', 1978);
insert into car (make, model, year_of_release) values ('BMW', '760', 2006);
insert into car (make, model, year_of_release) values ('Subaru', 'Baja', 2004);
insert into car (make, model, year_of_release) values ('Chevrolet', '2500', 1997);
insert into car (make, model, year_of_release) values ('Suzuki', 'Reno', 2007);
insert into car (make, model, year_of_release) values ('Honda', 'Insight', 2004);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', 'R-Class', 2011);
insert into car (make, model, year_of_release) values ('Nissan', 'Frontier', 2012);
insert into car (make, model, year_of_release) values ('Nissan', '350Z', 2005);
insert into car (make, model, year_of_release) values ('Nissan', 'Sentra', 2000);
insert into car (make, model, year_of_release) values ('Pontiac', 'Grand Prix', 1980);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Impala', 2008);
insert into car (make, model, year_of_release) values ('Geo', 'Prizm', 1996);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Malibu', 2003);
insert into car (make, model, year_of_release) values ('Bentley', 'Arnage', 2007);
insert into car (make, model, year_of_release) values ('Subaru', 'Forester', 2008);
insert into car (make, model, year_of_release) values ('Volkswagen', 'New Beetle', 2002);
insert into car (make, model, year_of_release) values ('Plymouth', 'Voyager', 1996);
insert into car (make, model, year_of_release) values ('GMC', 'Rally Wagon 3500', 1992);
insert into car (make, model, year_of_release) values ('Audi', 'S8', 2007);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Colorado', 2005);
insert into car (make, model, year_of_release) values ('Cadillac', 'DeVille', 1996);
insert into car (make, model, year_of_release) values ('Maybach', '62', 2005);
insert into car (make, model, year_of_release) values ('Porsche', '928', 1995);
insert into car (make, model, year_of_release) values ('Jaguar', 'XK Series', 2005);
insert into car (make, model, year_of_release) values ('Suzuki', 'Daewoo Magnus', 2004);
insert into car (make, model, year_of_release) values ('Pontiac', 'Firebird', 1993);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', 'CLS-Class', 2008);
insert into car (make, model, year_of_release) values ('Suzuki', 'Verona', 2004);
insert into car (make, model, year_of_release) values ('Ford', 'F450', 2008);
insert into car (make, model, year_of_release) values ('Hillman', 'Minx Magnificent', 1950);
insert into car (make, model, year_of_release) values ('Volkswagen', 'GTI', 2011);
insert into car (make, model, year_of_release) values ('Ford', 'LTD', 1984);
insert into car (make, model, year_of_release) values ('Toyota', 'MR2', 1994);
insert into car (make, model, year_of_release) values ('Ford', 'Model T', 1909);
insert into car (make, model, year_of_release) values ('Pontiac', 'Sunfire', 1997);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Express 3500', 1997);
insert into car (make, model, year_of_release) values ('Toyota', 'RAV4', 2003);
insert into car (make, model, year_of_release) values ('Ford', 'Explorer Sport Trac', 2009);
insert into car (make, model, year_of_release) values ('Dodge', 'Journey', 2012);
insert into car (make, model, year_of_release) values ('Lincoln', 'Mark LT', 2006);
insert into car (make, model, year_of_release) values ('Mercury', 'Marquis', 1985);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'Tredia', 1984);
insert into car (make, model, year_of_release) values ('Bentley', 'Continental Flying Spur', 2006);
insert into car (make, model, year_of_release) values ('Dodge', 'Dakota', 2006);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Equinox', 2012);
insert into car (make, model, year_of_release) values ('Mazda', 'CX-7', 2011);
insert into car (make, model, year_of_release) values ('Pontiac', 'Montana', 2004);
insert into car (make, model, year_of_release) values ('Subaru', 'Impreza', 2011);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Camaro', 2011);
insert into car (make, model, year_of_release) values ('Volkswagen', 'riolet', 1993);
insert into car (make, model, year_of_release) values ('Ford', 'F-Series', 1993);
insert into car (make, model, year_of_release) values ('Toyota', 'Corolla', 2005);
insert into car (make, model, year_of_release) values ('Ford', 'Econoline E250', 1995);
insert into car (make, model, year_of_release) values ('Volkswagen', 'Golf', 1989);
insert into car (make, model, year_of_release) values ('Ford', 'Econoline E350', 1995);
insert into car (make, model, year_of_release) values ('Pontiac', 'Grand Prix', 1983);
insert into car (make, model, year_of_release) values ('GMC', 'Savana 1500', 1996);
insert into car (make, model, year_of_release) values ('Honda', 'Accord Crosstour', 2010);
insert into car (make, model, year_of_release) values ('Ford', 'F350', 2009);
insert into car (make, model, year_of_release) values ('Bentley', 'Continental GT', 2006);
insert into car (make, model, year_of_release) values ('Dodge', 'Daytona', 1984);
insert into car (make, model, year_of_release) values ('Cadillac', 'SRX', 2006);
insert into car (make, model, year_of_release) values ('Lexus', 'LX', 1997);
insert into car (make, model, year_of_release) values ('Hyundai', 'Santa Fe', 2002);
insert into car (make, model, year_of_release) values ('Land Rover', 'Range Rover Sport', 2011);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Equinox', 2010);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'Expo', 1992);
insert into car (make, model, year_of_release) values ('Toyota', '4Runner', 2007);
insert into car (make, model, year_of_release) values ('Jeep', 'Grand Cherokee', 2010);
insert into car (make, model, year_of_release) values ('Hyundai', 'Elantra', 2013);
insert into car (make, model, year_of_release) values ('Lexus', 'RX', 2012);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Tahoe', 2005);
insert into car (make, model, year_of_release) values ('Jaguar', 'X-Type', 2005);
insert into car (make, model, year_of_release) values ('Mazda', 'B-Series', 2003);
insert into car (make, model, year_of_release) values ('Cadillac', 'Fleetwood', 1994);
insert into car (make, model, year_of_release) values ('Oldsmobile', 'LSS', 1998);
insert into car (make, model, year_of_release) values ('BMW', '7 Series', 2008);
insert into car (make, model, year_of_release) values ('Nissan', 'Altima', 2006);
insert into car (make, model, year_of_release) values ('Ford', 'F-Series', 2008);
insert into car (make, model, year_of_release) values ('Ford', 'Thunderbird', 1977);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Cavalier', 2004);
insert into car (make, model, year_of_release) values ('Mazda', 'Tribute', 2004);
insert into car (make, model, year_of_release) values ('Aston Martin', 'Vanquish S', 2005);
insert into car (make, model, year_of_release) values ('GMC', '2500', 1998);
insert into car (make, model, year_of_release) values ('Mazda', 'MX-5', 2006);
insert into car (make, model, year_of_release) values ('Dodge', 'Durango', 2012);
insert into car (make, model, year_of_release) values ('Ford', 'F-Series', 2003);
insert into car (make, model, year_of_release) values ('Kia', 'Sportage', 2002);
insert into car (make, model, year_of_release) values ('Mazda', 'Navajo', 1994);
insert into car (make, model, year_of_release) values ('Jaguar', 'XK Series', 2013);
insert into car (make, model, year_of_release) values ('BMW', 'M3', 2010);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', 'C-Class', 2000);
insert into car (make, model, year_of_release) values ('Mazda', 'MX-5', 1997);
insert into car (make, model, year_of_release) values ('Lincoln', 'MKX', 2012);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Colorado', 2010);
insert into car (make, model, year_of_release) values ('Isuzu', 'Amigo', 1998);
insert into car (make, model, year_of_release) values ('Lexus', 'ES', 1994);
insert into car (make, model, year_of_release) values ('Cadillac', 'Seville', 1999);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'Galant', 2001);
insert into car (make, model, year_of_release) values ('GMC', 'Sierra 3500', 2010);
insert into car (make, model, year_of_release) values ('Honda', 'Insight', 2004);
insert into car (make, model, year_of_release) values ('Land Rover', 'LR4', 2010);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'Outlander Sport', 2011);
insert into car (make, model, year_of_release) values ('Lexus', 'ES', 1999);
insert into car (make, model, year_of_release) values ('Buick', 'Lucerne', 2006);
insert into car (make, model, year_of_release) values ('Lincoln', 'Navigator', 2009);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Silverado 2500', 2002);
insert into car (make, model, year_of_release) values ('Mazda', 'Mazda6', 2010);
insert into car (make, model, year_of_release) values ('Infiniti', 'QX56', 2010);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'Mirage', 2001);
insert into car (make, model, year_of_release) values ('Volvo', 'V70', 1999);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Express 2500', 2001);
insert into car (make, model, year_of_release) values ('Lexus', 'SC', 2009);
insert into car (make, model, year_of_release) values ('Lexus', 'GS', 2005);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'Mirage', 1988);
insert into car (make, model, year_of_release) values ('Mitsubishi', '3000GT', 1996);
insert into car (make, model, year_of_release) values ('Suzuki', 'Aerio', 2007);
insert into car (make, model, year_of_release) values ('Dodge', 'Intrepid', 1994);
insert into car (make, model, year_of_release) values ('GMC', 'Savana 2500', 2006);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Camaro', 1999);
insert into car (make, model, year_of_release) values ('Mercury', 'Capri', 1984);
insert into car (make, model, year_of_release) values ('Suzuki', 'SJ', 1995);
insert into car (make, model, year_of_release) values ('Toyota', 'Tercel', 1994);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'Pajero', 1996);
insert into car (make, model, year_of_release) values ('Infiniti', 'I', 2001);
insert into car (make, model, year_of_release) values ('Rolls-Royce', 'Ghost', 2012);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', 'S-Class', 2005);
insert into car (make, model, year_of_release) values ('Nissan', 'Cube', 2009);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'Pajero', 1996);
insert into car (make, model, year_of_release) values ('Lexus', 'RX', 2009);
insert into car (make, model, year_of_release) values ('Audi', '80/90', 1988);
insert into car (make, model, year_of_release) values ('Lexus', 'GS', 1999);
insert into car (make, model, year_of_release) values ('Toyota', 'Land Cruiser', 2011);
insert into car (make, model, year_of_release) values ('Audi', '100', 1994);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'Lancer', 2002);
insert into car (make, model, year_of_release) values ('Ford', 'Aspire', 1997);
insert into car (make, model, year_of_release) values ('Chrysler', 'Town & Country', 2003);
insert into car (make, model, year_of_release) values ('Mazda', 'B-Series', 1994);
insert into car (make, model, year_of_release) values ('Ford', 'Edge', 2008);
insert into car (make, model, year_of_release) values ('Ford', 'Focus', 2006);
insert into car (make, model, year_of_release) values ('Hyundai', 'Tucson', 2006);
insert into car (make, model, year_of_release) values ('Cadillac', 'Brougham', 1992);
insert into car (make, model, year_of_release) values ('Ferrari', '599 GTB Fiorano', 2007);
insert into car (make, model, year_of_release) values ('Bentley', 'Continental GTC', 2010);
insert into car (make, model, year_of_release) values ('GMC', 'Savana', 2010);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Avalanche 1500', 2005);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Express 2500', 2004);
insert into car (make, model, year_of_release) values ('GMC', 'Sierra 1500', 2002);
insert into car (make, model, year_of_release) values ('Volvo', 'XC70', 2003);
insert into car (make, model, year_of_release) values ('Toyota', 'MR2', 2002);
insert into car (make, model, year_of_release) values ('Ford', 'Escape', 2004);
insert into car (make, model, year_of_release) values ('Cadillac', 'STS', 2010);
insert into car (make, model, year_of_release) values ('Nissan', 'Murano', 2011);
insert into car (make, model, year_of_release) values ('Chevrolet', '3500', 1994);
insert into car (make, model, year_of_release) values ('GMC', 'Savana 1500', 2002);
insert into car (make, model, year_of_release) values ('Plymouth', 'Voyager', 1993);
insert into car (make, model, year_of_release) values ('Chevrolet', 'G-Series 2500', 1997);
insert into car (make, model, year_of_release) values ('Mazda', 'MX-6', 1991);
insert into car (make, model, year_of_release) values ('Volkswagen', 'Passat', 1994);
insert into car (make, model, year_of_release) values ('Hyundai', 'Sonata', 2012);
insert into car (make, model, year_of_release) values ('Acura', 'NSX', 2001);
insert into car (make, model, year_of_release) values ('GMC', '3500 Club Coupe', 1993);
insert into car (make, model, year_of_release) values ('GMC', 'Canyon', 2005);
insert into car (make, model, year_of_release) values ('Lincoln', 'Continental', 1994);
insert into car (make, model, year_of_release) values ('Saturn', 'S-Series', 1993);
insert into car (make, model, year_of_release) values ('Dodge', 'Stealth', 1994);
insert into car (make, model, year_of_release) values ('GMC', 'Acadia', 2010);
insert into car (make, model, year_of_release) values ('Mercury', 'Mountaineer', 2004);
insert into car (make, model, year_of_release) values ('Cadillac', 'Escalade', 2010);
insert into car (make, model, year_of_release) values ('Pontiac', 'Vibe', 2010);
insert into car (make, model, year_of_release) values ('Toyota', 'Sequoia', 2002);
insert into car (make, model, year_of_release) values ('Toyota', '4Runner', 1993);
insert into car (make, model, year_of_release) values ('Volkswagen', 'Eos', 2009);
insert into car (make, model, year_of_release) values ('Ford', 'F-Series', 1994);
insert into car (make, model, year_of_release) values ('Lexus', 'CT', 2012);
insert into car (make, model, year_of_release) values ('Chrysler', 'Sebring', 2004);
insert into car (make, model, year_of_release) values ('Porsche', 'Cayman', 2008);
insert into car (make, model, year_of_release) values ('Nissan', 'Pathfinder', 2009);
insert into car (make, model, year_of_release) values ('BMW', 'X3', 2006);
insert into car (make, model, year_of_release) values ('Toyota', 'RAV4', 2001);
insert into car (make, model, year_of_release) values ('Mazda', 'B-Series', 2009);
insert into car (make, model, year_of_release) values ('Hyundai', 'Azera', 2009);
insert into car (make, model, year_of_release) values ('Toyota', 'Sienna', 1998);
insert into car (make, model, year_of_release) values ('Toyota', 'Corolla', 1997);
insert into car (make, model, year_of_release) values ('Mazda', 'B-Series', 1988);
insert into car (make, model, year_of_release) values ('Toyota', 'Supra', 1997);
insert into car (make, model, year_of_release) values ('Eagle', 'Summit', 1993);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Astro', 1998);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', 'W126', 1981);
insert into car (make, model, year_of_release) values ('GMC', 'Envoy XL', 2006);
insert into car (make, model, year_of_release) values ('Dodge', 'Ram Van 2500', 2000);
insert into car (make, model, year_of_release) values ('Dodge', 'Ram Wagon B250', 1994);
insert into car (make, model, year_of_release) values ('Buick', 'Electra', 1986);
insert into car (make, model, year_of_release) values ('Pontiac', 'Trans Sport', 1999);
insert into car (make, model, year_of_release) values ('Maserati', 'Quattroporte', 2011);
insert into car (make, model, year_of_release) values ('Ford', 'Tempo', 1991);
insert into car (make, model, year_of_release) values ('Mazda', 'Protege', 1996);
insert into car (make, model, year_of_release) values ('Suzuki', 'Sidekick', 1991);
insert into car (make, model, year_of_release) values ('GMC', 'Envoy', 2003);
insert into car (make, model, year_of_release) values ('Volkswagen', 'Golf', 1992);
insert into car (make, model, year_of_release) values ('Subaru', 'Forester', 2009);
insert into car (make, model, year_of_release) values ('Oldsmobile', 'Ciera', 1992);
insert into car (make, model, year_of_release) values ('BMW', 'M5', 1993);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', 'E-Class', 2000);
insert into car (make, model, year_of_release) values ('Lamborghini', 'Murciélago', 2007);
insert into car (make, model, year_of_release) values ('Chrysler', 'Concorde', 1998);
insert into car (make, model, year_of_release) values ('GMC', 'Sierra 2500', 2007);
insert into car (make, model, year_of_release) values ('Jaguar', 'XJ Series', 1997);
insert into car (make, model, year_of_release) values ('Ford', 'Mustang', 1965);
insert into car (make, model, year_of_release) values ('Buick', 'Park Avenue', 1999);
insert into car (make, model, year_of_release) values ('Honda', 'CR-V', 2012);
insert into car (make, model, year_of_release) values ('Chrysler', 'Town & Country', 2006);
insert into car (make, model, year_of_release) values ('Pontiac', 'Aztek', 2002);
insert into car (make, model, year_of_release) values ('Mercury', 'Grand Marquis', 2005);
insert into car (make, model, year_of_release) values ('Kia', 'Sorento', 2006);
insert into car (make, model, year_of_release) values ('Ford', 'Mustang', 1997);
insert into car (make, model, year_of_release) values ('Bentley', 'Continental GTC', 2008);
insert into car (make, model, year_of_release) values ('Cadillac', 'Allante', 1992);
insert into car (make, model, year_of_release) values ('Audi', 'Coupe GT', 1987);
insert into car (make, model, year_of_release) values ('Lexus', 'LX', 2001);
insert into car (make, model, year_of_release) values ('Porsche', 'Carrera GT', 2005);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', 'SL-Class', 1987);
insert into car (make, model, year_of_release) values ('Ford', 'Windstar', 2003);
insert into car (make, model, year_of_release) values ('Ford', 'GT', 2006);
insert into car (make, model, year_of_release) values ('Jeep', 'Liberty', 2005);
insert into car (make, model, year_of_release) values ('Dodge', 'Viper', 2002);
insert into car (make, model, year_of_release) values ('Ferrari', '612 Scaglietti', 2006);
insert into car (make, model, year_of_release) values ('Saab', '9-5', 2002);
insert into car (make, model, year_of_release) values ('Pontiac', 'Trans Sport', 1994);
insert into car (make, model, year_of_release) values ('Ford', 'F350', 2007);
insert into car (make, model, year_of_release) values ('Chrysler', 'Concorde', 1996);
insert into car (make, model, year_of_release) values ('Saturn', 'VUE', 2009);
insert into car (make, model, year_of_release) values ('Lexus', 'RX', 2013);
insert into car (make, model, year_of_release) values ('Pontiac', '6000', 1990);
insert into car (make, model, year_of_release) values ('Subaru', 'Impreza', 2004);
insert into car (make, model, year_of_release) values ('GMC', 'Vandura G2500', 1995);
insert into car (make, model, year_of_release) values ('Dodge', 'Grand Caravan', 2001);
insert into car (make, model, year_of_release) values ('GMC', 'Savana 2500', 2009);
insert into car (make, model, year_of_release) values ('Saturn', 'VUE', 2004);
insert into car (make, model, year_of_release) values ('Volvo', 'C70', 2004);
insert into car (make, model, year_of_release) values ('Subaru', 'Legacy', 2009);
insert into car (make, model, year_of_release) values ('Ford', 'E-Series', 1963);
insert into car (make, model, year_of_release) values ('Mazda', '626', 1998);
insert into car (make, model, year_of_release) values ('Land Rover', 'Range Rover', 1989);
insert into car (make, model, year_of_release) values ('Volkswagen', 'Cabriolet', 1990);
insert into car (make, model, year_of_release) values ('Ford', 'F350', 2006);
insert into car (make, model, year_of_release) values ('Ford', 'Windstar', 1999);
insert into car (make, model, year_of_release) values ('Kia', 'Spectra', 2004);
insert into car (make, model, year_of_release) values ('GMC', 'Sonoma', 1994);
insert into car (make, model, year_of_release) values ('Dodge', 'Caravan', 2000);
insert into car (make, model, year_of_release) values ('Dodge', 'Intrepid', 1993);
insert into car (make, model, year_of_release) values ('Infiniti', 'Q', 1999);
insert into car (make, model, year_of_release) values ('Isuzu', 'Rodeo Sport', 2003);
insert into car (make, model, year_of_release) values ('Chevrolet', 'G-Series G20', 1993);
insert into car (make, model, year_of_release) values ('Mazda', 'B-Series Plus', 2002);
insert into car (make, model, year_of_release) values ('Dodge', 'Ram', 2007);
insert into car (make, model, year_of_release) values ('Kia', 'Sportage', 2007);
insert into car (make, model, year_of_release) values ('Saturn', 'VUE', 2004);
insert into car (make, model, year_of_release) values ('Kia', 'Soul', 2011);
insert into car (make, model, year_of_release) values ('Chevrolet', '3500', 2000);
insert into car (make, model, year_of_release) values ('Lexus', 'HS', 2011);
insert into car (make, model, year_of_release) values ('Volkswagen', 'Jetta', 1984);
insert into car (make, model, year_of_release) values ('Aptera', 'Typ-1', 2009);
insert into car (make, model, year_of_release) values ('Ford', 'E350', 2009);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Corvette', 1963);
insert into car (make, model, year_of_release) values ('Maybach', '57', 2012);
insert into car (make, model, year_of_release) values ('Dodge', 'Neon', 2000);
insert into car (make, model, year_of_release) values ('Chrysler', 'Sebring', 2004);
insert into car (make, model, year_of_release) values ('Toyota', '4Runner', 1998);
insert into car (make, model, year_of_release) values ('Pontiac', 'Grand Prix', 1974);
insert into car (make, model, year_of_release) values ('Dodge', 'Ram', 1994);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', 'CL-Class', 2005);
insert into car (make, model, year_of_release) values ('Pontiac', 'Firefly', 1987);
insert into car (make, model, year_of_release) values ('Toyota', 'Corolla', 2008);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Express 2500', 2005);
insert into car (make, model, year_of_release) values ('Volkswagen', 'Eurovan', 2001);
insert into car (make, model, year_of_release) values ('Ford', 'Mustang', 2007);
insert into car (make, model, year_of_release) values ('Toyota', 'Tacoma', 2005);
insert into car (make, model, year_of_release) values ('GMC', 'Sierra 1500', 2012);
insert into car (make, model, year_of_release) values ('Hyundai', 'Sonata', 2007);
insert into car (make, model, year_of_release) values ('Porsche', 'Carrera GT', 2004);
insert into car (make, model, year_of_release) values ('Ford', 'Explorer', 1992);
insert into car (make, model, year_of_release) values ('Ford', 'Freestar', 2007);
insert into car (make, model, year_of_release) values ('Subaru', 'Justy', 1991);
insert into car (make, model, year_of_release) values ('Ford', 'Explorer', 2003);
insert into car (make, model, year_of_release) values ('Volkswagen', 'Golf', 2010);
insert into car (make, model, year_of_release) values ('Nissan', 'Altima', 1994);
insert into car (make, model, year_of_release) values ('Volvo', 'S40', 2008);
insert into car (make, model, year_of_release) values ('Volvo', 'S80', 2001);
insert into car (make, model, year_of_release) values ('Ford', 'Contour', 1999);
insert into car (make, model, year_of_release) values ('GMC', 'Sierra 1500', 2010);
insert into car (make, model, year_of_release) values ('Dodge', 'Grand Caravan', 2010);
insert into car (make, model, year_of_release) values ('Mercury', 'Grand Marquis', 2008);
insert into car (make, model, year_of_release) values ('Lincoln', 'Navigator', 2011);
insert into car (make, model, year_of_release) values ('Subaru', 'Justy', 1988);
insert into car (make, model, year_of_release) values ('Ford', 'Escort', 1987);
insert into car (make, model, year_of_release) values ('Pontiac', 'Trans Sport', 1997);
insert into car (make, model, year_of_release) values ('Hyundai', 'Tiburon', 2000);
insert into car (make, model, year_of_release) values ('Lincoln', 'Town Car', 2007);
insert into car (make, model, year_of_release) values ('Honda', 'Prelude', 1993);
insert into car (make, model, year_of_release) values ('BMW', 'X5', 2003);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'Diamante', 2005);
insert into car (make, model, year_of_release) values ('Chrysler', 'Fifth Ave', 1993);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Corvette', 1984);
insert into car (make, model, year_of_release) values ('Ford', 'Expedition', 2004);
insert into car (make, model, year_of_release) values ('Chrysler', 'Cirrus', 1995);
insert into car (make, model, year_of_release) values ('Hyundai', 'Scoupe', 1995);
insert into car (make, model, year_of_release) values ('Lincoln', 'Town Car', 1996);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Colorado', 2012);
insert into car (make, model, year_of_release) values ('Maserati', 'Quattroporte', 2005);
insert into car (make, model, year_of_release) values ('Plymouth', 'Colt', 1993);
insert into car (make, model, year_of_release) values ('Acura', 'RL', 2001);
insert into car (make, model, year_of_release) values ('Mazda', 'RX-7', 1985);
insert into car (make, model, year_of_release) values ('Suzuki', 'XL-7', 2005);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Express 3500', 2008);
insert into car (make, model, year_of_release) values ('Ford', 'Club Wagon', 1995);
insert into car (make, model, year_of_release) values ('Saab', '9000', 1991);
insert into car (make, model, year_of_release) values ('Suzuki', 'SJ', 1989);
insert into car (make, model, year_of_release) values ('Geo', 'Tracker', 1992);
insert into car (make, model, year_of_release) values ('Maserati', 'Spyder', 1991);
insert into car (make, model, year_of_release) values ('Volvo', 'S80', 2007);
insert into car (make, model, year_of_release) values ('Saturn', 'VUE', 2008);
insert into car (make, model, year_of_release) values ('Cadillac', 'Eldorado', 1999);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', 'R-Class', 2010);
insert into car (make, model, year_of_release) values ('BMW', '7 Series', 1992);
insert into car (make, model, year_of_release) values ('Honda', 'CR-V', 1999);
insert into car (make, model, year_of_release) values ('Isuzu', 'Ascender', 2005);
insert into car (make, model, year_of_release) values ('Ford', 'F350', 2000);
insert into car (make, model, year_of_release) values ('Volkswagen', 'CC', 2012);
insert into car (make, model, year_of_release) values ('Lotus', 'Elise', 2008);
insert into car (make, model, year_of_release) values ('BMW', 'M3', 2001);
insert into car (make, model, year_of_release) values ('Morgan', 'Aero 8', 2007);
insert into car (make, model, year_of_release) values ('Volvo', '850', 1993);
insert into car (make, model, year_of_release) values ('Volkswagen', 'New Beetle', 1999);
insert into car (make, model, year_of_release) values ('GMC', 'Yukon XL 2500', 2004);
insert into car (make, model, year_of_release) values ('Volvo', 'S40', 2005);
insert into car (make, model, year_of_release) values ('Ford', 'F350', 2011);
insert into car (make, model, year_of_release) values ('Mazda', 'RX-7', 1994);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'Lancer Evolution', 2003);
insert into car (make, model, year_of_release) values ('Maybach', '57S', 2005);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'Lancer', 2011);
insert into car (make, model, year_of_release) values ('Jeep', 'Cherokee', 1993);
insert into car (make, model, year_of_release) values ('Mazda', 'MX-5', 1992);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Caprice Classic', 1993);
insert into car (make, model, year_of_release) values ('Infiniti', 'IPL G', 2011);
insert into car (make, model, year_of_release) values ('Mazda', 'Tribute', 2002);
insert into car (make, model, year_of_release) values ('Pontiac', 'Sunfire', 1999);
insert into car (make, model, year_of_release) values ('Audi', 'Allroad', 2002);
insert into car (make, model, year_of_release) values ('GMC', 'Envoy XL', 2003);
insert into car (make, model, year_of_release) values ('Nissan', 'Leaf', 2011);
insert into car (make, model, year_of_release) values ('Ford', 'Laser', 1987);
insert into car (make, model, year_of_release) values ('Mazda', 'RX-7', 1995);
insert into car (make, model, year_of_release) values ('Buick', 'Century', 1992);
insert into car (make, model, year_of_release) values ('Cadillac', 'Fleetwood', 1996);
insert into car (make, model, year_of_release) values ('Mercury', 'Cougar', 2002);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'Montero', 1994);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Metro', 2000);
insert into car (make, model, year_of_release) values ('Ford', 'Thunderbird', 1965);
insert into car (make, model, year_of_release) values ('Nissan', 'Rogue', 2011);
insert into car (make, model, year_of_release) values ('Ford', 'Expedition', 2001);
insert into car (make, model, year_of_release) values ('Audi', 'A3', 2011);
insert into car (make, model, year_of_release) values ('Jeep', 'Liberty', 2011);
insert into car (make, model, year_of_release) values ('Nissan', 'Altima', 2010);
insert into car (make, model, year_of_release) values ('Audi', 'A4', 1998);
insert into car (make, model, year_of_release) values ('Chevrolet', 'S10 Blazer', 1992);
insert into car (make, model, year_of_release) values ('Isuzu', 'Rodeo', 2003);
insert into car (make, model, year_of_release) values ('Dodge', 'Intrepid', 2003);
insert into car (make, model, year_of_release) values ('GMC', 'Savana 3500', 2002);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'Lancer', 2001);
insert into car (make, model, year_of_release) values ('Isuzu', 'VehiCROSS', 1999);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', 'W201', 1992);
insert into car (make, model, year_of_release) values ('Hummer', 'H2', 2004);
insert into car (make, model, year_of_release) values ('Honda', 'Accord', 2011);
insert into car (make, model, year_of_release) values ('Toyota', 'RAV4', 2006);
insert into car (make, model, year_of_release) values ('Lamborghini', 'Gallardo', 2008);
insert into car (make, model, year_of_release) values ('Lincoln', 'Town Car', 1990);
insert into car (make, model, year_of_release) values ('Mercury', 'Topaz', 1984);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'Galant', 1996);
insert into car (make, model, year_of_release) values ('Audi', 'S4', 2001);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'Starion', 1988);
insert into car (make, model, year_of_release) values ('Geo', 'Prizm', 1995);
insert into car (make, model, year_of_release) values ('Dodge', 'Dakota Club', 1998);
insert into car (make, model, year_of_release) values ('Mazda', 'Miata MX-5', 2002);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Venture', 2001);
insert into car (make, model, year_of_release) values ('Eagle', 'Talon', 1997);
insert into car (make, model, year_of_release) values ('Lexus', 'LS', 1994);
insert into car (make, model, year_of_release) values ('Volkswagen', 'Golf', 2000);
insert into car (make, model, year_of_release) values ('Ford', 'Thunderbird', 2005);
insert into car (make, model, year_of_release) values ('Mazda', 'CX-5', 2013);
insert into car (make, model, year_of_release) values ('Saab', '9-5', 2002);
insert into car (make, model, year_of_release) values ('Hyundai', 'Elantra', 1996);
insert into car (make, model, year_of_release) values ('Saab', '9000', 1995);
insert into car (make, model, year_of_release) values ('GMC', 'Savana 3500', 2008);
insert into car (make, model, year_of_release) values ('Saab', '900', 1998);
insert into car (make, model, year_of_release) values ('Dodge', 'Dakota', 1998);
insert into car (make, model, year_of_release) values ('Subaru', 'Impreza', 2006);
insert into car (make, model, year_of_release) values ('Mercury', 'Mystique', 1995);
insert into car (make, model, year_of_release) values ('Isuzu', 'Hombre', 1998);
insert into car (make, model, year_of_release) values ('Subaru', 'Legacy', 2008);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'Montero', 2004);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Cobalt', 2010);
insert into car (make, model, year_of_release) values ('Alfa Romeo', 'Spider', 1992);
insert into car (make, model, year_of_release) values ('Ford', 'Taurus', 2008);
insert into car (make, model, year_of_release) values ('Subaru', 'Legacy', 2005);
insert into car (make, model, year_of_release) values ('Pontiac', 'Montana', 2000);
insert into car (make, model, year_of_release) values ('Mercury', 'Milan', 2006);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', 'M-Class', 2000);
insert into car (make, model, year_of_release) values ('Dodge', 'Ram 2500 Club', 1996);
insert into car (make, model, year_of_release) values ('Lexus', 'RX', 2004);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Suburban 1500', 1997);
insert into car (make, model, year_of_release) values ('Cadillac', 'STS', 2011);
insert into car (make, model, year_of_release) values ('Ford', 'Tempo', 1986);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', 'S-Class', 1990);
insert into car (make, model, year_of_release) values ('Ford', 'Escort', 1996);
insert into car (make, model, year_of_release) values ('Nissan', 'Altima', 2003);
insert into car (make, model, year_of_release) values ('Toyota', 'Tacoma', 2007);
insert into car (make, model, year_of_release) values ('Buick', 'Riviera', 1979);
insert into car (make, model, year_of_release) values ('Mercury', 'Sable', 1991);
insert into car (make, model, year_of_release) values ('Jeep', 'Grand Cherokee', 2003);
insert into car (make, model, year_of_release) values ('Pontiac', 'Grand Am', 1998);
insert into car (make, model, year_of_release) values ('MINI', 'Cooper', 2003);
insert into car (make, model, year_of_release) values ('Suzuki', 'XL7', 2006);
insert into car (make, model, year_of_release) values ('Subaru', 'Tribeca', 2010);
insert into car (make, model, year_of_release) values ('Dodge', 'Ramcharger', 1992);
insert into car (make, model, year_of_release) values ('Toyota', 'Land Cruiser', 1996);
insert into car (make, model, year_of_release) values ('Porsche', 'Boxster', 2006);
insert into car (make, model, year_of_release) values ('Pontiac', 'Sunfire', 2001);
insert into car (make, model, year_of_release) values ('GMC', 'Yukon XL 2500', 2001);
insert into car (make, model, year_of_release) values ('Pontiac', 'Grand Prix', 1986);
insert into car (make, model, year_of_release) values ('Audi', 'A5', 2011);
insert into car (make, model, year_of_release) values ('Subaru', 'B9 Tribeca', 2007);
insert into car (make, model, year_of_release) values ('Mitsubishi', '3000GT', 1992);
insert into car (make, model, year_of_release) values ('Kia', 'Rondo', 2010);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Silverado 3500', 2002);
insert into car (make, model, year_of_release) values ('Chevrolet', '3500', 2000);
insert into car (make, model, year_of_release) values ('Buick', 'Lucerne', 2006);
insert into car (make, model, year_of_release) values ('Oldsmobile', '88', 1998);
insert into car (make, model, year_of_release) values ('Lotus', 'Elan', 1992);
insert into car (make, model, year_of_release) values ('Hummer', 'H1', 1994);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', '300TE', 1993);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'Lancer Evolution', 2006);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', 'CLK-Class', 2002);
insert into car (make, model, year_of_release) values ('Honda', 'Civic', 1991);
insert into car (make, model, year_of_release) values ('Ford', 'Taurus', 1995);
insert into car (make, model, year_of_release) values ('Volkswagen', 'GTI', 2006);
insert into car (make, model, year_of_release) values ('Subaru', 'Outback', 2009);
insert into car (make, model, year_of_release) values ('Cadillac', 'SRX', 2012);
insert into car (make, model, year_of_release) values ('Ford', 'Focus', 2006);
insert into car (make, model, year_of_release) values ('Nissan', 'Armada', 2005);
insert into car (make, model, year_of_release) values ('Mercury', 'Sable', 2003);
insert into car (make, model, year_of_release) values ('Ford', 'Econoline E350', 1992);
insert into car (make, model, year_of_release) values ('Volkswagen', 'Vanagon', 1984);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'GTO', 1990);
insert into car (make, model, year_of_release) values ('Dodge', 'Caravan', 2009);
insert into car (make, model, year_of_release) values ('Suzuki', 'XL7', 2008);
insert into car (make, model, year_of_release) values ('Chrysler', 'Cirrus', 2000);
insert into car (make, model, year_of_release) values ('Toyota', 'Supra', 1996);
insert into car (make, model, year_of_release) values ('Subaru', 'Legacy', 1991);
insert into car (make, model, year_of_release) values ('Buick', 'Coachbuilder', 1992);
insert into car (make, model, year_of_release) values ('Hyundai', 'Entourage', 2009);
insert into car (make, model, year_of_release) values ('Buick', 'Skyhawk', 1989);
insert into car (make, model, year_of_release) values ('Infiniti', 'G', 2002);
insert into car (make, model, year_of_release) values ('Plymouth', 'Fury', 1964);
insert into car (make, model, year_of_release) values ('Lincoln', 'Town Car', 2007);
insert into car (make, model, year_of_release) values ('Volkswagen', 'Tiguan', 2009);
insert into car (make, model, year_of_release) values ('Honda', 'Crosstour', 2012);
insert into car (make, model, year_of_release) values ('Dodge', 'Caravan', 1985);
insert into car (make, model, year_of_release) values ('Suzuki', 'SX4', 2008);
insert into car (make, model, year_of_release) values ('Nissan', 'Altima', 2006);
insert into car (make, model, year_of_release) values ('Ford', 'ZX2', 2001);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'Montero', 2005);
insert into car (make, model, year_of_release) values ('Ford', 'Mustang', 2001);
insert into car (make, model, year_of_release) values ('Rolls-Royce', 'Phantom', 2005);
insert into car (make, model, year_of_release) values ('Volkswagen', 'New Beetle', 2002);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Suburban 1500', 2012);
insert into car (make, model, year_of_release) values ('Ford', 'LTD', 1986);
insert into car (make, model, year_of_release) values ('Volkswagen', 'New Beetle', 2001);
insert into car (make, model, year_of_release) values ('Honda', 'Accord', 2007);
insert into car (make, model, year_of_release) values ('Pontiac', 'Firefly', 1987);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Traverse', 2011);
insert into car (make, model, year_of_release) values ('Ford', 'Five Hundred', 2007);
insert into car (make, model, year_of_release) values ('Ford', 'E350', 2006);
insert into car (make, model, year_of_release) values ('Ford', 'Freestyle', 2005);
insert into car (make, model, year_of_release) values ('Mazda', 'MPV', 1992);
insert into car (make, model, year_of_release) values ('Dodge', 'Ram 1500', 1995);
insert into car (make, model, year_of_release) values ('Volvo', 'S80', 2005);
insert into car (make, model, year_of_release) values ('Hyundai', 'Sonata', 1998);
insert into car (make, model, year_of_release) values ('Dodge', 'Caliber', 2012);
insert into car (make, model, year_of_release) values ('GMC', 'Yukon XL 2500', 2011);
insert into car (make, model, year_of_release) values ('BMW', '5 Series', 1997);
insert into car (make, model, year_of_release) values ('Toyota', 'RAV4', 2001);
insert into car (make, model, year_of_release) values ('Volvo', 'XC90', 2013);
insert into car (make, model, year_of_release) values ('Bentley', 'Mulsanne', 2011);
insert into car (make, model, year_of_release) values ('Nissan', 'Titan', 2010);
insert into car (make, model, year_of_release) values ('Ford', 'Explorer', 1997);
insert into car (make, model, year_of_release) values ('Subaru', 'Legacy', 2007);
insert into car (make, model, year_of_release) values ('Pontiac', 'Aztek', 2005);
insert into car (make, model, year_of_release) values ('Audi', 'A8', 2010);
insert into car (make, model, year_of_release) values ('Mazda', 'B2500', 2001);
insert into car (make, model, year_of_release) values ('Oldsmobile', '88', 1995);
insert into car (make, model, year_of_release) values ('Dodge', 'Nitro', 2009);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', 'G-Class', 2011);
insert into car (make, model, year_of_release) values ('Mazda', 'Mazdaspeed 3', 2012);
insert into car (make, model, year_of_release) values ('Ford', 'F250', 2005);
insert into car (make, model, year_of_release) values ('Jeep', 'Wrangler', 2004);
insert into car (make, model, year_of_release) values ('Jaguar', 'X-Type', 2005);
insert into car (make, model, year_of_release) values ('Ford', 'E-Series', 1988);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', '300E', 1992);
insert into car (make, model, year_of_release) values ('Ford', 'Mustang', 1998);
insert into car (make, model, year_of_release) values ('BMW', '5 Series', 2006);
insert into car (make, model, year_of_release) values ('Lexus', 'LX', 2005);
insert into car (make, model, year_of_release) values ('Toyota', 'Land Cruiser', 2009);
insert into car (make, model, year_of_release) values ('Toyota', 'Tercel', 1993);
insert into car (make, model, year_of_release) values ('Nissan', 'Pathfinder', 2000);
insert into car (make, model, year_of_release) values ('Mazda', 'RX-8', 2010);
insert into car (make, model, year_of_release) values ('Ford', 'F250', 2008);
insert into car (make, model, year_of_release) values ('Lincoln', 'MKS', 2012);
insert into car (make, model, year_of_release) values ('Buick', 'Terraza', 2007);
insert into car (make, model, year_of_release) values ('Honda', 'Accord', 1994);
insert into car (make, model, year_of_release) values ('Nissan', 'Quest', 2002);
insert into car (make, model, year_of_release) values ('Jaguar', 'X-Type', 2006);
insert into car (make, model, year_of_release) values ('BMW', 'Z3', 2001);
insert into car (make, model, year_of_release) values ('Lexus', 'LX', 2010);
insert into car (make, model, year_of_release) values ('Ford', 'Contour', 1998);
insert into car (make, model, year_of_release) values ('Volkswagen', 'Jetta', 2009);
insert into car (make, model, year_of_release) values ('Honda', 'Civic', 1990);
insert into car (make, model, year_of_release) values ('Chevrolet', 'Silverado 1500', 2004);
insert into car (make, model, year_of_release) values ('Nissan', 'Altima', 1995);
insert into car (make, model, year_of_release) values ('Eagle', 'Summit', 1996);
insert into car (make, model, year_of_release) values ('Acura', 'TSX', 2009);
insert into car (make, model, year_of_release) values ('Toyota', 'Solara', 2003);
insert into car (make, model, year_of_release) values ('Nissan', 'Xterra', 2007);
insert into car (make, model, year_of_release) values ('Ford', 'ZX2', 2001);
insert into car (make, model, year_of_release) values ('Bentley', 'Arnage', 2006);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', 'CL-Class', 2012);
insert into car (make, model, year_of_release) values ('GMC', 'Safari', 1992);
insert into car (make, model, year_of_release) values ('Lexus', 'GS', 1997);
insert into car (make, model, year_of_release) values ('Toyota', 'Camry', 1992);
insert into car (make, model, year_of_release) values ('Chevrolet', '1500', 1993);
insert into car (make, model, year_of_release) values ('GMC', 'Sierra 3500', 2008);
insert into car (make, model, year_of_release) values ('Pontiac', 'Bonneville', 2004);
insert into car (make, model, year_of_release) values ('Saab', '900', 1987);
insert into car (make, model, year_of_release) values ('Ford', 'E-Series', 2006);
insert into car (make, model, year_of_release) values ('GMC', 'Savana 3500', 1999);
insert into car (make, model, year_of_release) values ('Dodge', 'Dakota Club', 2000);
insert into car (make, model, year_of_release) values ('Mercedes-Benz', 'E-Class', 1989);
insert into car (make, model, year_of_release) values ('Mitsubishi', 'Chariot', 1986);
insert into car (make, model, year_of_release) values ('Audi', '80', 1990);
insert into car (make, model, year_of_release) values ('Oldsmobile', 'Bravada', 1993);
insert into car (make, model, year_of_release) values ('BMW', '3 Series', 1993);
insert into car (make, model, year_of_release) values ('Cadillac', 'CTS-V', 2011);
insert into car (make, model, year_of_release) values ('Toyota', 'Avalon', 2009);
insert into car (make, model, year_of_release) values ('Ford', 'Focus', 2007);