name: Continuous Integration for Develop Branch

on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Start databases defined in docker-compose.yml
        run: docker compose up -d

      - name: Set up JDK 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Maven verify phase
        run: mvn --batch-mode --update-snapshots verify

      - name: Stop and remove databases
        run: docker compose down